### Invoke root of server
GET http://localhost:3300/


### Get all tasks
GET http://localhost:3300/tasks 
Content-Type: application/json

### Get task by id
GET http://localhost:3300/tasks/2
Content-Type: application/json


### Get all tasks
POST http://localhost:3300/tasks 
Content-Type: application/json

{
    "title": "Tarea 1",
    "detail": "Detalle de la tarea 1"
}

### Update a task
PUT http://localhost:3300/tasks/1
Content-Type: application/json

{
    "title": "Tarea modificada",
    "detail": "detalle modificado"
}

### Update a task with query parameter
PUT http://localhost:3300/tasks/1?status=PENDING
Content-Type: application/json

{
    "title": "Tarea modificada",
    "detail": "detalle modificado"
}

### Delte a task
DELETE http://localhost:3300/tasks/1

